### ISSUE TITLE
How to generat audio-visual synthetic data ??

### ISSUE THREAD

**Issue by zoey9628** [aromanusc/SoundQ#18]
Thank you for providing the code. I have downloaded the youtube video and tried to run audiovisual_synth.py, but it cannot run. I have some questions, and hope you can help me to answer them:
1. It is mentioned in the paper that METU-SPARG RIR data is used, and the files used in the code are em32(AIR data), which one should be chosen actually?
2. There is no file named IR_em32.wav in the METU-SPARG dataset. Why is this file loaded in the code? Does this file need to be generated extra?
![image](https://github.com/aromanusc/SoundQ/assets/120021259/aaa57384-73b4-4a09-927f-607226365dca)

3. Can you provide a readme for generating audio-visual synthetic data?

Looking forward to your reply very much!!!! :)

**Comment by zoey9628** [comment]
> Hey thanks for reaching out.
> 
> I have added a simple README under `synth_data_gen`, which I hope can help.
> 
> I am going to add more work and cleanup to this repo in the upcoming days. If you have any questions, please let me know, I am happy to help and assist.

Thanks for your reply!! After I updated the code, this problem occurred, but I don't quite understand it. Could you please help me check it?
![image](https://github.com/aromanusc/SoundQ/assets/120021259/a3922da3-cec2-4606-a7a4-e0754325226e)

**Comment by aromanusc** [comment]
Nice! Are you able to generate synthetic audiovisual scenes now?

To keep things in sync we mainly need to make sure that we extract the audio completely from the video. So if the video for example is 1.33 seconds long, the audio has to be 1.33 seconds long. When we spatialize the audio the same thing occurs for each sound event.

**Comment by zoey9628** [comment]
> Nice! Are you able to generate synthetic audiovisual scenes now?
> 
> To keep things in sync we mainly need to make sure that we extract the audio completely from the video. So if the video for example is 1.33 seconds long, the audio has to be 1.33 seconds long. When we spatialize the audio the same thing occurs for each sound event.

Yes, I have generated synthetic audiovisual scenes :)
According to your description, only the length of audio and video captured is guaranteed.   Is it necessary to make the audio and video clips start at the same time?
For example: need to use 1.33 seconds long in 001.MP4, video clips from 1:00 to 2:33, must the audio clips from 1:00 to 2:33? Is it right the  audio clips from 0:00 to 1:33? How do you keep audio and video clips from the same start time and the same end time?
I found the basis for the start time of the video clip in the code as shown below, but I did not find the basis for the start time of the audio clip.
![image](https://github.com/aromanusc/SoundQ/assets/120021259/752b0206-0eea-4f71-900c-10ea54f1ebce)

**Comment by adrianSRoman** [comment]
Yeah, so when we generate a synthetic audiovisual event the steps are: generate metadata, generate video, generate audio. Both the video and audio generation are based upon the metadata. Take a look at the metadata csv files under `/output/metadata`. That is what we use in order to determine at what frame a given video and audio scene should show up. When we generate video and audio you will also see `events_history`, that is what we use to populate the events as we generate the synthetic data.

**Comment by adrianSRoman** [comment]
> For example: need to use 1.33 seconds long in 001.MP4, video clips from 1:00 to 2:33, must the audio clips from 1:00 to 2:33?

Correct

**Comment by adrianSRoman** [comment]
The basis for audio is the event_history, which is the metadata shared by the audio and video generators. This is where we use it for audio: https://github.com/aromanusc/SoundQ/blob/34b613e729701a8c2a8d9452ae9370b3e6a1085c/synth_data_gen/audiovisual_synth.py#L98

**Comment by zoey9628** [comment]
> The basis for audio is the event_history, which is the metadata shared by the audio and video generators. This is where we use it for audio:
> 
> https://github.com/aromanusc/SoundQ/blob/34b613e729701a8c2a8d9452ae9370b3e6a1085c/synth_data_gen/audiovisual_synth.py#L98

Thanks for your reply. I also have another question: when write metadata DCASE format, why `frame_step = 3` for audiovisual? the code:
https://github.com/aromanusc/SoundQ/blob/34b613e729701a8c2a8d9452ae9370b3e6a1085c/synth_data_gen/metadata_generator.py#L121

**Comment by adrianSRoman** [comment]
> Thanks for your reply. I also have another question: when write metadata DCASE format, why frame_step = 3 for audiovisual?

This is related to the dact that the DCASE format metadata contains labels for 100ms of audio. When dealing with video sampled at 30fps, to make up 1 dcase frame we need 3 video frames (100ms). Thus, for each metadata frame we need to step and place in the video canvas 3 video frames.

**Comment by adrianSRoman** [comment]
Btw, for optimal performance with your models, I strongly recommend getting really high-quality videos with high-quality audio.

**Comment by zoey9628** [comment]
> > Thanks for your reply. I also have another question: when write metadata DCASE format, why frame_step = 3 for audiovisual?
> 
> This is related to the fact that the DCASE format metadata contains labels for 100ms of audio. When dealing with video sampled at 30fps, to make up 1 DCASE frame we need 3 video frames (100ms). Thus, for each metadata frame we need to step and place in the video canvas 3 video frames.

Oh I see. Thank you for your patience in answering my questions  : )

**Comment by aromanusc** [comment]
No problem! Feel free to open up more issues if more support is needed.
